@baseUrl = http://localhost:3000
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/signup
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "dwerdd",
  "password": "",
  "email": "fwef@yahoo.com",
  "avatarColor": "dwded",
  "avatarImage": "<add-a-base64-encoded-string>"
}
